const GALLETAS = [
  {
    id: 'la-clasica',
    nombre: 'La Clásica',
    sabor: 'chispas-chocolate',
    decoracion: 'ninguna',
    descripcion: 'classsssssssssssssssssssss',
    precio: 3500,
    categoria: 'clasicas',
    etiquetas: ['Más vendida', 'Chocolate'],
    favorita: true,
  },
  {
    id: 'doble-chocolate',
    nombre: 'Doble Chocolate',
    sabor: 'doble-chocolate',
    decoracion: 'ninguna',
    descripcion: 'Masa de cacao con trozos de chocolate que quedan blanditos por dentro.',
    precio: 4200,
    categoria: 'chocolate',
    etiquetas: ['Intensa', 'Cacao 70%'],
    favorita: true,
  },
  {
    id: 'red-velvet',
    nombre: 'Red Velvet',
    sabor: 'red-velvet',
    decoracion: 'corazon',
    descripcion: 'La roja de la casa, con chocolate blanco y un corazón de glaseado encima.',
    precio: 4500,
    categoria: 'especiales',
    etiquetas: ['Chocolate blanco', 'Para regalar'],
    favorita: true,
  },
  {
    id: 'confeti-magico',
    nombre: 'Confeti Mágico',
    sabor: 'vainilla-confeti',
    decoracion: 'grageas',
    descripcion: 'Vainilla con grageas de colores. Es la que siempre piden para los cumpleaños.',
    precio: 4000,
    categoria: 'especiales',
    etiquetas: ['Cumpleaños', 'Colorida'],
    favorita: false,
  },
  {
    id: 'avena-canela',
    nombre: 'Avena y Canela',
    sabor: 'avena-canela',
    decoracion: 'ninguna',
    descripcion: 'Avena en hojuelas, canela y uvas pasas. Menos dulce y llena más.',
    precio: 3200,
    categoria: 'clasicas',
    etiquetas: ['Menos dulce', 'Con avena'],
    favorita: false,
  },
  {
    id: 'limon-glaseado',
    nombre: 'Limón Glaseado',
    sabor: 'limon',
    decoracion: 'glaseado',
    descripcion: 'Galleta de limón con glaseado blanco que cruje apenas la muerdes.',
    precio: 4300,
    categoria: 'especiales',
    etiquetas: ['Cítrica', 'Glaseada'],
    favorita: false,
  },
  {
    id: 'mantequilla-mani',
    nombre: 'Mantequilla de Maní',
    sabor: 'mantequilla-mani',
    decoracion: 'ninguna',
    descripcion: 'Con mantequilla de maní de verdad y una pizca de sal para equilibrar.',
    precio: 4100,
    categoria: 'clasicas',
    etiquetas: ['Contiene maní', 'Salada y dulce'],
    favorita: false,
  },
  {
    id: 'brownie-nuez',
    nombre: 'Brownie de Nuez',
    sabor: 'brownie-nuez',
    decoracion: 'estrellas',
    descripcion: 'Mitad galleta, mitad brownie. Con nueces y estrellitas de azúcar.',
    precio: 4800,
    categoria: 'chocolate',
    etiquetas: ['Contiene nueces', 'Muy jugosa'],
    favorita: true,
  },
  {
    id: 'avena-sin-azucar',
    nombre: 'Avena sin Azúcar',
    sabor: 'avena-canela',
    decoracion: 'ninguna',
    descripcion: 'Endulzada solo con banano y dátiles. Pensada para quien cuida el azúcar.',
    precio: 3900,
    categoria: 'sin-azucar',
    etiquetas: ['Sin azúcar añadida', 'Integral'],
    favorita: false,
  },
];
