const GALLETAS = [
  {
    id: 'doble-chocolate',
    nombre: 'Doble Chocolate',
    sabor: 'doble-chocolate',
    decoracion: 'ninguna',
    descripcion: 'Cubierta de Nutella con trozos de chocolatina, cereal crocante y chips de chocolate.',
    precio: 4200,
    categoria: 'galletas',
    etiquetas: ['Intensa', 'Cacao 70%'],
    favorita: true,
    foto: 'img/galleta-doble-chocolate.jpg',
  },
  {
    id: 'confeti-magico',
    nombre: 'Confeti Mágico',
    sabor: 'vainilla-confeti',
    decoracion: 'grageas',
    descripcion: 'Cubierta de Nutella con grageas de colores y chips de chocolate. La de los cumpleaños.',
    precio: 4000,
    categoria: 'galletas',
    etiquetas: ['Cumpleaños', 'Colorida'],
    favorita: true,
    foto: 'img/galleta-confeti.jpg',
  },
  {
    id: 'fresa-banano',
    nombre: 'Fresa y Banano',
    sabor: 'avena-canela',
    decoracion: 'ninguna',
    descripcion: 'Cubierta de Nutella con fresas, rodajas de banano y hojuelas de avena.',
    precio: 4500,
    categoria: 'galletas',
    etiquetas: ['Con fruta', 'Nutella'],
    favorita: true,
    foto: 'img/galleta-fresa-banano.jpg',
  },
  {
    id: 'topinc-fresa',
    nombre: 'Fresa',
    tipo: 'topinc',
    sabor: 'vainilla-confeti',
    decoracion: 'ninguna',
    descripcion: 'Fresas frescas en trozos para ponerle encima a tu galleta.',
    precio: 1000,
    categoria: 'topincs',
    etiquetas: ['Fruta', 'Fresca'],
    favorita: false,
    foto: 'img/topinc-fresa.jpg',
  },
  {
    id: 'topinc-banano',
    nombre: 'Banano',
    tipo: 'topinc',
    sabor: 'vainilla-confeti',
    decoracion: 'ninguna',
    descripcion: 'Rodajas de banano maduro, dulce y suavecito.',
    precio: 1000,
    categoria: 'topincs',
    etiquetas: ['Fruta', 'Dulce'],
    favorita: false,
    foto: 'img/topinc-banano.jpg',
  },
  {
    id: 'topinc-grageas',
    nombre: 'Grageas de colores',
    tipo: 'topinc',
    sabor: 'vainilla-confeti',
    decoracion: 'ninguna',
    descripcion: 'Grageas largas de todos los colores para una galleta más alegre.',
    precio: 1000,
    categoria: 'topincs',
    etiquetas: ['Colorida', 'Crocante'],
    favorita: false,
    foto: 'img/topinc-grageas.jpg',
  },
  {
    id: 'topinc-chochitos',
    nombre: 'Chochitos de colores',
    tipo: 'topinc',
    sabor: 'vainilla-confeti',
    decoracion: 'ninguna',
    descripcion: 'Bolitas de azúcar de colores, las de los cumpleaños.',
    precio: 1000,
    categoria: 'topincs',
    etiquetas: ['Colorida', 'Crocante'],
    favorita: false,
    foto: 'img/topinc-chochitos.jpg',
  },
  {
    id: 'topinc-cereal',
    nombre: 'Cereal',
    tipo: 'topinc',
    sabor: 'vainilla-confeti',
    decoracion: 'ninguna',
    descripcion: 'Cereal crocante con sabor a chocolate.',
    precio: 1000,
    categoria: 'topincs',
    etiquetas: ['Crocante', 'Chocolate'],
    favorita: false,
    foto: 'img/topinc-cereal.jpg',
  },
];
